spring: 
  profiles:
    active:
    - dev
---
spring: 
  profiles: dev
  application:
    name: microconfig-test-dev
server:
  port: 8201
eureka:
  client:
    service-url:
      defaultZone: http://edmin:mldnjava@eureka-dev.com:7001/eureka
---
spring: 
  profiles: beta
  application:
    name: microconfig-test-defaule
server:
  port: 8202
eureka:
  client:
    service-url:
      defaultZone: http://edmin:mldnjava@eureka-beta.com:7001/eureka